[package]
name = "chipbox-scene"
version = "0.1.0"
edition = "2024"

[dependencies]
delegate-match = "0.2.0"
serde = { version = "1.0.219", features = ["derive", "rc"] }
ts-rs = { version = "11.0.1", features = ["format"] }

[lints]
workspace = true
